name: CI

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

jobs:
  docker-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Build CI image (amd64)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          build-args: |
            INSTALL_PROFILE=ci
          tags: housing-allinone:ci
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run pytest inside the image
        run: |
          docker run --rm \
            -e TEST_MODE=1 \
            housing-allinone:ci \
            python -m pytest -q
