name: CI

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image for runner arch (amd64)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          build-args: |
            ARCH=amd64
          tags: housing-allinone:ci
          load: true   # load into local Docker on the runner, not pushing

      - name: Run tests inside the image
        run: |
          docker run --rm \
            -e TEST_MODE=1 \
            housing-allinone:ci \
            sh -lc 'uv pip install --system pytest && uv run pytest -q'
